# Config guide at https://alacritty.org/config-alacritty.html

[general]
import = [
    "alacritty-theme/themes/citylights.toml"
]

[window]
padding = { x = 5, y = 5 }

[scrolling]
history = 100000

[font]
normal = { family = "Menlo", style = "Regular" }
size = 13.5
offset = {x = 1, y = 1}

# Shell stuff (mac arm)

[terminal.shell]
program = "/opt/homebrew/bin/bash"
args = ["-l"]

[env]
SHELL="/opt/homebrew/bin/bash"


[terminal]
osc52 = "OnlyCopy"

