# Config guide at https://alacritty.org/config-alacritty.html

[general]
import = [
    #"alacritty-theme/themes/gruvbox_dark.toml"
]

[window]
padding = { x = 5, y = 5 }

[scrolling]
history = 100000

[font]
normal = { family = "Menlo", style = "Regular" }
size = 12.5
offset = {x = 1, y = 1}

[terminal.shell]
program = "/opt/homebrew/bin/bash"
args = ["-l"]

[terminal]
osc52 = "OnlyCopy"


