require('plugins')
require('user.vimoptions') 
require('user.nvimoptions')
require('user.zenmode')
require('user.gitsigns')
require('user.colors')
require('user.telescope')
require('user.treesitter')
require('user.lspsettings')
require('user.lspserverconfig')
require('user.autocomplete')
require('user.smear')
require('user.startup')
require('user.osc52')
require('user.fterm')

require('zettel')
